{
 "title": "perfstats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "EliteDesk Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "issue_resource_value{group=\"mem\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EliteDesk Swap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "issue_resource_value{group=\"mem\", resource_name=\"swap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EliteDesk All CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "issue_resource_value{group=\"cpu\", resource_name=\"cpu:all\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EliteDesk Network (Err in and out PPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "avg(issue_resource_value{group=\"net\", resource_property_name=\"errin-pps\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(issue_resource_value{group=\"net\", resource_property_name=\"err-out-pps\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EliteDesk Network Wireless",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "issue_resource_value{group=\"net\", resource_name=\"nic:wlx7cdd907366a2\", resource_property_name=\"recv-pps\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "issue_resource_value{group=\"net\", resource_name=\"nic:wlx7cdd907366a2\", resource_property_name=\"sent-pps\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}